### ISSUE TITLE
docs: Updated README about differences between local and production environment

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/bennu-official#158]
# AsIs
No descriptions of differences between local environment by docker-compose and production environment with GKE.

# ToDo
- [x] fix upstream config of proxy_path in `manifests/configs/nginx.conf` from `http://django.bennuhp.svc.cluster.local:8000/` to localhost port
- [ ] ~adjust health checking (probing) with `mysqladmin`~
- [x] add test procedures in local environment
- [x] add setup instructions for user not using docker/OrbStack environment

# (Optional) Acceptance criteria
N/A

# (Optional) Additional contexts
N/A

**Comment by hwakabh** [comment]
Regarding adjustment of `mysqladmin` interval, since we had already tuned and fixed in https://github.com/hwakabh/bennu-official/pull/194, removed from ToDo.
